filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/logs/*.log

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"] # Refers to name from docker-compose.yml
  index: "nginx"

setup.template.name: "nginx"
setup.template.pattern: "nginx-*"